// ============================================================
//  POOLRIDE — Dummy Data
//  Used while your backend is not ready. 
//  Replace by connecting real API responses from apiService.js
// ============================================================

export const DUMMY_USER = {
  id: 'usr_001',
  name: 'Arjun Sharma',
  email: 'arjun.sharma@gmail.com',
  phone: '+91 98765 43210',
  avatar: 'https://i.pravatar.cc/150?img=12',
  rating: 4.8,
  totalRides: 47,
  isDriver: true,
  isVerified: true,
  memberSince: '2023-01-15',
  wallet: { balance: 1250.00, currency: 'INR' },
  preferences: {
    smoking: false,
    pets: false,
    music: true,
    chat: 'talkative',
  },
};

export const DUMMY_RIDES = [
  {
    id: 'ride_001',
    driver: {
      id: 'usr_002',
      name: 'Rahul Verma',
      avatar: 'https://i.pravatar.cc/150?img=8',
      rating: 4.9,
      totalRides: 123,
      isVerified: true,
    },
    from: { name: 'New Delhi', full: 'New Delhi, Connaught Place', lat: 28.6329, lng: 77.2195 },
    to: { name: 'Agra', full: 'Agra, Uttar Pradesh', lat: 27.1767, lng: 78.0081 },
    date: '2025-06-15',
    time: '07:00 AM',
    duration: '3h 30m',
    distance: '233 km',
    seatsAvailable: 2,
    totalSeats: 3,
    pricePerSeat: 350,
    vehicle: { name: 'Swift Dzire', model: 'Maruti Suzuki', color: 'White', number: 'DL 4C 1234' },
    preferences: { smoking: false, pets: false, music: true, ac: true },
    stops: ['Mathura', 'Vrindavan'],
    status: 'upcoming',
    instantBook: true,
  },
  {
    id: 'ride_002',
    driver: {
      id: 'usr_003',
      name: 'Priya Patel',
      avatar: 'https://i.pravatar.cc/150?img=23',
      rating: 4.7,
      totalRides: 89,
      isVerified: true,
    },
    from: { name: 'New Delhi', full: 'New Delhi, India Gate', lat: 28.6129, lng: 77.2295 },
    to: { name: 'Jaipur', full: 'Jaipur, Rajasthan', lat: 26.9124, lng: 75.7873 },
    date: '2025-06-15',
    time: '06:30 AM',
    duration: '5h 00m',
    distance: '280 km',
    seatsAvailable: 3,
    totalSeats: 4,
    pricePerSeat: 450,
    vehicle: { name: 'Innova Crysta', model: 'Toyota', color: 'Silver', number: 'RJ 14 AB 5678' },
    preferences: { smoking: false, pets: true, music: false, ac: true },
    stops: ['Gurugram', 'Neemrana'],
    status: 'upcoming',
    instantBook: false,
  },
  {
    id: 'ride_003',
    driver: {
      id: 'usr_004',
      name: 'Karan Singh',
      avatar: 'https://i.pravatar.cc/150?img=15',
      rating: 4.6,
      totalRides: 56,
      isVerified: false,
    },
    from: { name: 'Gurugram', full: 'Gurugram, DLF Phase 1', lat: 28.4595, lng: 77.0266 },
    to: { name: 'Chandigarh', full: 'Chandigarh, Sector 17', lat: 30.7333, lng: 76.7794 },
    date: '2025-06-15',
    time: '08:00 AM',
    duration: '4h 00m',
    distance: '250 km',
    seatsAvailable: 1,
    totalSeats: 2,
    pricePerSeat: 400,
    vehicle: { name: 'Creta', model: 'Hyundai', color: 'Black', number: 'HR 26 CD 9012' },
    preferences: { smoking: false, pets: false, music: true, ac: true },
    stops: ['Ambala'],
    status: 'upcoming',
    instantBook: true,
  },
  {
    id: 'ride_004',
    driver: {
      id: 'usr_005',
      name: 'Ananya Gupta',
      avatar: 'https://i.pravatar.cc/150?img=47',
      rating: 5.0,
      totalRides: 210,
      isVerified: true,
    },
    from: { name: 'Mumbai', full: 'Mumbai, Bandra Kurla Complex', lat: 19.0760, lng: 72.8777 },
    to: { name: 'Pune', full: 'Pune, Hinjewadi', lat: 18.5204, lng: 73.8567 },
    date: '2025-06-16',
    time: '09:00 AM',
    duration: '2h 30m',
    distance: '148 km',
    seatsAvailable: 2,
    totalSeats: 3,
    pricePerSeat: 250,
    vehicle: { name: 'Nexon EV', model: 'Tata', color: 'Blue', number: 'MH 02 EF 3456' },
    preferences: { smoking: false, pets: false, music: true, ac: true },
    stops: [],
    status: 'upcoming',
    instantBook: true,
  },
];

export const DUMMY_MY_BOOKINGS = [
  {
    id: 'booking_001',
    rideId: 'ride_001',
    status: 'confirmed',
    seats: 2,
    totalAmount: 700,
    paymentStatus: 'paid',
    paymentMethod: 'UPI',
    bookedAt: '2025-06-10T10:30:00Z',
    ride: DUMMY_RIDES[0],
  },
  {
    id: 'booking_002',
    rideId: 'ride_005',
    status: 'completed',
    seats: 1,
    totalAmount: 350,
    paymentStatus: 'paid',
    paymentMethod: 'Wallet',
    bookedAt: '2025-05-20T08:00:00Z',
    ride: {
      ...DUMMY_RIDES[0],
      id: 'ride_005',
      date: '2025-05-22',
      from: { name: 'Delhi', full: 'New Delhi Railway Station' },
      to: { name: 'Mathura', full: 'Mathura, UP' },
      status: 'completed',
    },
  },
  {
    id: 'booking_003',
    rideId: 'ride_006',
    status: 'cancelled',
    seats: 1,
    totalAmount: 450,
    paymentStatus: 'refunded',
    paymentMethod: 'Card',
    bookedAt: '2025-05-01T09:00:00Z',
    ride: {
      ...DUMMY_RIDES[1],
      id: 'ride_006',
      date: '2025-05-05',
      status: 'cancelled',
    },
  },
];

export const DUMMY_NOTIFICATIONS = [
  {
    id: 'notif_001',
    type: 'booking_confirmed',
    title: 'Booking Confirmed! 🎉',
    body: 'Your seat on Delhi → Agra is confirmed for June 15.',
    isRead: false,
    createdAt: '2025-06-10T10:30:00Z',
  },
  {
    id: 'notif_002',
    type: 'ride_reminder',
    title: 'Ride Tomorrow! ⏰',
    body: 'Your ride with Rahul departs at 7:00 AM from Connaught Place.',
    isRead: false,
    createdAt: '2025-06-14T18:00:00Z',
  },
  {
    id: 'notif_003',
    type: 'new_review',
    title: 'New Review',
    body: 'Priya left you a 5-star review. "Great co-passenger!"',
    isRead: true,
    createdAt: '2025-06-08T14:20:00Z',
  },
  {
    id: 'notif_004',
    type: 'promo',
    title: 'Get ₹100 Off! 🎁',
    body: 'Use code POOL100 on your next 3 rides. Valid till June 30.',
    isRead: true,
    createdAt: '2025-06-05T09:00:00Z',
  },
];

export const DUMMY_POPULAR_ROUTES = [
  { id: 'r1', from: 'Delhi', to: 'Agra', rides: 24, minPrice: 300 },
  { id: 'r2', from: 'Delhi', to: 'Jaipur', rides: 18, minPrice: 400 },
  { id: 'r3', from: 'Mumbai', to: 'Pune', rides: 32, minPrice: 200 },
  { id: 'r4', from: 'Bangalore', to: 'Mysuru', rides: 15, minPrice: 150 },
  { id: 'r5', from: 'Chennai', to: 'Pondicherry', rides: 10, minPrice: 180 },
];

export const DUMMY_REVIEWS = [
  {
    id: 'rev_001',
    reviewer: { name: 'Sneha M.', avatar: 'https://i.pravatar.cc/150?img=32' },
    rating: 5,
    comment: 'Amazing driver! Very punctual, clean car, and great conversation.',
    createdAt: '2025-05-28',
  },
  {
    id: 'rev_002',
    reviewer: { name: 'Vikram J.', avatar: 'https://i.pravatar.cc/150?img=18' },
    rating: 4,
    comment: 'Good experience overall. Would definitely ride again.',
    createdAt: '2025-05-15',
  },
  {
    id: 'rev_003',
    reviewer: { name: 'Meera R.', avatar: 'https://i.pravatar.cc/150?img=44' },
    rating: 5,
    comment: 'Safe driver, comfortable journey. Highly recommend!',
    createdAt: '2025-04-30',
  },
];